mtg_card_identifier/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("mtg_card_identifier_web.urls", namespace="mtg_card_identifier_web")),
]

mtg_card_identifier_web/urls.py
from django.conf.urls import url
from django.contrib import admin

from mtg_card_identifier_web.views import IndexView, DebugView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'debug/$', DebugView.as_view(), name="debug"),
]

mtg_card_identifier_core/models.py
from django.db import models

# Create your models here.

mtg_card_identifier_web/models.py
from django.db import models

# Create your models here.

mtg_card_identifier_web/forms.py
from django import forms


class UploadImageForm(forms.Form):
    image = forms.FileField()

mtg_card_identifier_core/views.py
from django.shortcuts import render

# Create your views here.

mtg_card_identifier_web/views.py
import json
import os

from django.shortcuts import render
from django.views.generic import View

from mtg_card_identifier_core.opencv_mtg_identifier import identify_file
from mtg_card_identifier_web.forms import UploadImageForm

BASE_DIR = os.path.dirname(__file__)
LATEST_DIR = os.path.join(BASE_DIR, "../mtg_card_identifier_core/static/latest")
DEBUG_FILE = os.path.join(LATEST_DIR, "latest_debug.json")

class IndexView(View):

    def get(self, request):
        context = {
            "form": UploadImageForm(),
        }

        return render(request, "mtg_card_identifier_web/index.html", context)

    def post(self, request):
        context = {
            "result": None,
        }
        form = UploadImageForm(request.POST, request.FILES)
        context["form"] = form

        if form.is_valid():
            card = identify_file(request.FILES['image'].file.name, True)
            context["result"] = json.dumps(card, indent=4, sort_keys=True)
            context["card"] = card

        return render(request, "mtg_card_identifier_web/index.html", context)


class DebugView(View):

    def get(self, request):
        context = {}

        with open(DEBUG_FILE) as data_file:
            data = json.load(data_file)

        context["debug_data"] = json.dumps(data, indent=4, sort_keys=True)

        return render(request, "mtg_card_identifier_web/debug.html", context)

mtg_card_identifier_web/templates/mtg_card_identifier_web/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<!--
	Eventually by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<!--[if lte IE 8]><script src="{% static "mtg_card_identifier_web/assets/js/ie/html5shiv.js" %}"></script><![endif]-->
		<link rel="stylesheet" href="{% static "mtg_card_identifier_web/assets/css/main.css" %}" />
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static "mtg_card_identifier_web/assets/css/ie8.css" %}" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static "mtg_card_identifier_web/assets/css/ie9.css" %}" /><![endif]-->
	</head>
	<body>
        {% block content %}{% endblock %}
		<!-- Footer -->
		<footer id="footer">
			<ul class="copyright">
				<li>&copy; Alexandre Arpin.</li><li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li><li>Credits: <a href="http://html5up.net">HTML5 UP</a></li>
			</ul>
		</footer>

		<!-- Scripts -->
		<!--[if lte IE 8]><script src="{% static "mtg_card_identifier_web/assets/js/ie/respond.min.js" %}"></script><![endif]-->
		<script src="{% static "mtg_card_identifier_web/assets/js/main.js" %}"></script>
        <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
	</body>
</html>

mtg_card_identifier_web/templates/mtg_card_identifier_web/debug.html
{% extends "mtg_card_identifier_web/base.html" %}
{% load staticfiles %}

{% block title %}Magic the Gathering Card Detector {% endblock %}

{% block content %}
    <!-- Header -->
    <header id="header">
        <h1>Debug</h1>
    </header>

    <h3>Identifier Debug</h3>
    <pre><code class="prettyprint">{{ debug_data }}</code></pre>


    <h3>Raw</h3>
    <div><img src="{% static "latest/latest_raw.jpg" %}"></div>

    <h3>Crop</h3>
    <div><img src="{% static "latest/latest_crop.jpg" %}"></div>

    <h3>Name Crop</h3>
    <div>
        <img src="{% static "latest/latest_name.jpg" %}">
    </div>

    <h3>Text Crop</h3>
    <div>
        <img src="{% static "latest/latest_text.jpg" %}">
    </div>

    <h3>Type Crop</h3>
    <div>
        <img src="{% static "latest/latest_type.jpg" %}">
    </div>

    <h3>Number and Edition Crop</h3>
    <div>
        <img src="{% static "latest/latest_number.jpg" %}">
    </div>



{% endblock %}

mtg_card_identifier_web/templates/mtg_card_identifier_web/index.html
{% extends "mtg_card_identifier_web/base.html" %}

{% block title %}Magic the Gathering Card Detector {% endblock %}

{% block content %}
    <!-- Header -->
    <header id="header">
        <h1>Magic the Gathering Card Detector</h1>
        <p>Upload, paste or link an image containing a Magic the Gathering card (M15, KTK, FRF, DTK, ORI and BFZ only)</p>
    </header>

    <!-- Upload Form -->
    <form id="signup-form" method="post" action="{% url "mtg_card_identifier_web:index" %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.image }}
        <input type="submit" value="Push it" />
    </form>
    {% if result %}
        <div>
            <h1>Result - {{ card.name }}</h1>
            <div class="flexbox-container">
                <div style="width:20%;">
                    <img src="http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid={{ card.multiverseid }}&type=card">
                </div>
                <div style="width:80%;">
                    <pre><code class="prettyprint">{{ result }}</code></pre>
                </div>
            </div>
        </div>
    {% endif %}


{% endblock %}